// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKeeed1DF_r9JJs48rh1lPE0VBIi5InY4',
    appId: '1:892147136037:web:d95f81510f50384a8f71cc',
    messagingSenderId: '892147136037',
    projectId: 'vehicle-management-csvtu',
    authDomain: 'vehicle-management-csvtu.firebaseapp.com',
    storageBucket: 'vehicle-management-csvtu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SwHqbrysCE1BjhQ3wvpG2PjCToy36M0',
    appId: '1:892147136037:android:c629b7bd9d6066e68f71cc',
    messagingSenderId: '892147136037',
    projectId: 'vehicle-management-csvtu',
    storageBucket: 'vehicle-management-csvtu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvaEVhwIsdwZWp451LUlh1IaswgXYeT88',
    appId: '1:892147136037:ios:d200f8c9e27d0bfc8f71cc',
    messagingSenderId: '892147136037',
    projectId: 'vehicle-management-csvtu',
    storageBucket: 'vehicle-management-csvtu.appspot.com',
    iosBundleId: 'com.example.vehicleManagementApp',
  );
}
